### PR TITLE
Fix nginx plugin so it can be run for an nginx container

### PR DESCRIPTION
**Pull request by alexdias**
Most of the logic that allows it to do so will be in a plugin_helper.

### CODE REVIEW

**Comment by alexdias** [comment]
Bear in mind it needs this: https://github.com/outlyerapp/plugin-helper/pull/1

And I think we need to fix the parsing as the metrics were wrong for me (wasn't counting my 200 status codes) but that should go on a different commit.

**Review by aymanosman — APPROVED** [review]

**Comment by tomashley** [comment]
This looks good. I assume it will still fail on containers with no `ps`?

**Comment by alexdias** [comment]
@tomashley Correct. Should we handle that? I can also patch a function that would get running processes (it would use container.top())

**Review by tradel — APPROVED** [review]

**Comment by aymanosman** [comment]
@alexdias actually I think we shouldn't fail if the container doesn't have `ps`, that is ridiculous.

**Comment by alexdias** [comment]
@aymanosman Well...

https://github.com/moby/moby/blob/7d8bf5d177127c61208e397bf8cf53b2f52ac9e7/daemon/top_unix.go#L145

Can you test what `docker container top` does for your container that doesnt have ps?

**Comment by tomashley** [comment]
merging.We can iterate on the `ps` piece

**Pull request merged**
